services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: mt_nginx
    restart: always
    environment:
      PS1: "NGINX container: $$(pwd)# "
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./my_django_template/static:/usr/share/nginx/my_django_template_static:ro"
    depends_on:
    - my_django_template
    ports:
    - "80:80"
    - "443:443"
  my_django_template_db:
    image: postgres:15.3-alpine3.18
    container_name: mt_db
    restart: always
    environment:
      PS1: "my_django_template database container: $$(pwd)# "
      POSTGRES_PASSWORD: CrappyPassword
      POSTGRES_USER: user
      POSTGRES_DB: my_django_template
    volumes:
    - my_django_template_db:/var/lib/postgresql/data
    - "/etc/timezone:/etc/timezone:ro"
    - "/usr/share/zoneinfo/Europe/Stockholm:/etc/localtime:ro"
  my_django_template:
    image: localhost/my_django_template:latest
    container_name: mt_django
    restart: always
    depends_on:
    - my_django_template_db
    environment:
      PS1: "my_django_template container: $$(pwd)# "
      PYTHONPATH: "/code"
    volumes:
    - "./site:/code/site:rw"
    - "/etc/timezone:/etc/timezone:ro"
    - "/usr/share/zoneinfo/Europe/Stockholm:/etc/localtime:ro"
    command: >
      sh -c "rm -rf /code/site/static/* &&
             /code/venv/bin/python /code/site/manage.py collectstatic &&
             uwsgi /code/site/uwsgi.ini"
volumes:
  my_django_template_db:

